artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingest
  source_url: wine_quality.csv
  local_data_file: artifacts/data_ingest/wine_quality.csv
  unzip_dir: artifacts/data_ingest

data_validation: 
  root_dir: artifacts/data_validate
  unzip_dir: artifacts/data_ingest/wine_quality.csv
  STATUS_FILE: artifacts/data_validate/status.txt