artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingest
  source_url: wine_quality.csv
  local_data_file: artifacts/data_ingest/wine_quality.csv
  unzip_dir: artifacts/data_ingest

data_validation: 
  root_dir: artifacts/data_validate
  unzip_dir: artifacts/data_ingest/wine_quality.csv
  STATUS_FILE: artifacts/data_validate/status.txt

data_transform:
  root_dir: artifacts/data_transform
  data_path: artifacts/data_ingest/wine_quality.csv

model_trainer: 
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transform/train.csv
  test_data_path: artifacts/data_transform/test.csv
  model_name: model.joblib